version: '3'
services:

  service-admin:
    build: anair-service-admin
    container_name: anair-service-admin
    ports:
      - 18080:18080

  service-rest:
    build: anair-service-rest
    container_name: anair-service-rest
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://service-admin:18080/admin
      - BASEURL_SERVICE_C=http://service-proto:8083/anair-service-proto
      - OPENTRACING_JAEGER_UDP-SENDER_HOST=jaeger
      - SPRING.KAFKA.BOOTSTRAPSERVERS=localhost:9092
      - LOG_APPENDER=LOGSTASH_STDOUT
      - LOG_LEVEL=INFO
    depends_on:
      - kafka
    links:
      - fluentd
    ports:
      - 8081:8081
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service-rest

  service-kafka:
    build: anair-service-kafka
    container_name: anair-service-kafka
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://service-admin:18080/admin
      - OPENTRACING_JAEGER_UDP-SENDER_HOST=jaeger
      - SPRING.KAFKA.BOOTSTRAPSERVERS=kafka:9092
      - LOG_APPENDER=LOGSTASH_STDOUT
      - LOG_LEVEL=INFO
    depends_on:
      - kafka
    links:
      - fluentd
    ports:
      - 8082:8082
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service-kafka

  service-proto:
    build: anair-service-proto
    container_name: anair-service-proto
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://service-admin:18080/admin
      - OPENTRACING_JAEGER_UDP-SENDER_HOST=jaeger
      - LOG_APPENDER=LOGSTASH_STDOUT
      - LOG_LEVEL=INFO
    ports:
      - 8083:8083
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service-proto

networks:
  default:
    external:
      name: spring-boot-microservices_default