version: '3'
services:

  fluentd:
    build: logging/fluentd
    container_name: fluentd
    volumes:
      - ./logging/fluentd/conf:/fluentd/etc
    ports:
      - 24224:24224

  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    restart: on-failure
    ports:
      - 2181:2181
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: zookeeper

  kafka:
    image: wurstmeister/kafka:2.12-2.3.1
    container_name: kafka
    restart: on-failure
    hostname: kafka
    depends_on:
      - zookeeper
    links:
      - fluentd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    ports:
      - 9092:9092
      - 9094:9094
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: kafka

networks:
  default:
    external:
      name: spring-boot-microservices_default