version: '3'
services:

##---- Infrastructure services ----##
  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaeger
    restart: on-failure
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8090:8080

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure
    ports:
      - 9090:9090
    volumes:
      - ./metrics/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - "--log.level=error"
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    depends_on:
      - cadvisor
      - node-exporter

  loki:
    image: grafana/loki
    container_name: loki
    restart: on-failure
    ports:
      - 3100:3100
    command:
      - "-config.file=/etc/loki/loki-config.yaml"
    volumes:
      - ./metrics/loki/conf:/etc/loki/

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "104"
    restart: on-failure
    depends_on:
      - prometheus
      - loki
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./metrics/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./metrics/grafana/grafana.env

  elasticsearch:
    image: amazon/opendistro-for-elasticsearch
    container_name: elasticsearch
    restart: on-failure
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - discovery.type=single-node
      - opendistro_security.ssl.transport.enabled=true
      - opendistro_security.ssl.http.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana
    container_name: kibana
    restart: on-failure
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  prometheus_data: {}
  grafana_data: {}
