global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'anair-services'

scrape_configs:

  - job_name: 'service-a'
    metrics_path: '/anair-service-a/actuator/prometheus'
    static_configs:
      - targets: ['service-a:8080']

  - job_name: 'service-b'
    metrics_path: '/anair-service-b/actuator/prometheus'
    static_configs:
        - targets: ['service-b:8081']

  - job_name: 'service-c'
    metrics_path: '/anair-service-c/actuator/prometheus'
    static_configs:
        - targets: ['service-c:8082']

  - job_name: 'cadvisor'
    static_configs:
        - targets: ['cadvisor:8090','node-exporter:9100']


