apiVersion: v1
kind: Service
metadata:
  name: service-a-service
  labels:
    app: service-a
  namespace: anair
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: service-a
  type: NodePort